DEFAULT_DOMAINS = [
    "information theory",
    "statistical mechanics",
    "evolutionary biology",
    "control theory",
    "network science",
    "game theory",
    "thermodynamics",
    "ecology",
    "economics",
    "immunology",
    "materials science",
    "fluid dynamics",
    "epidemiology",
    "signal processing",
    "quantum mechanics",
    "category theory",
    "complex systems",
    "cybernetics",
    "topology",
    "crystallography",
]
